run:
  bsz: 10000

ckpt:
  load_ckpt: True
  name: 'checkpoints/step-18000.pt'

es:
  random_search: False
  population_size: 100
  parent_size: 20
  mutation_size: 40
  mutation_prob: 0.5
  crossover_size: 40
  n_iterations: 40
  est_success_rate: False
  score_mode: loss_succ
  gene_mask: null
  eval:
    use_noise_model: False
    use_real_qc: False
    bsz: qiskit_max
    n_test_samples: 150
  legalize_layout: False

dataset:
  split: valid
