model:
  arch:
    sample_arch: [[0, 1, 2, 3], [0, 1, 2, 3], [0, 1, 2, 3], [], [[0, 1], [1, 2], [2, 3]], [], [], [], [], [], [], [0, 1, 2], [[2, 3]], [3], [0, 1, 2, 3], [0, 2, 3], [[2, 3], [1, 2]], [2], [1, 2], [1], [[2, 3], [1, 2]], [3], [0, 2, 3], [0], [[0, 1], [2, 3]], [1], [1, 2], [1, 2], [[2, 3]], [1], [1, 2, 3], [0, 1, 2, 3], [[0, 1], [2, 3]], 2]