callbacks:
- callback: SubnetInferenceRunner
  split: valid
  subcallbacks:
  - metrics: CategoricalAccuracy
    name: superacc/smallest_valid
  - metrics: NLLError
    name: superloss/smallest_valid
  subnet: smallest
- callback: SubnetInferenceRunner
  split: valid
  subcallbacks:
  - metrics: CategoricalAccuracy
    name: superacc/middle_valid
  - metrics: NLLError
    name: superloss/middle_valid
  subnet: middle
- callback: SubnetInferenceRunner
  split: valid
  subcallbacks:
  - metrics: CategoricalAccuracy
    name: superacc/largest_valid
  - metrics: NLLError
    name: superloss/largest_valid
  subnet: largest
- callback: SubnetInferenceRunner
  split: valid
  subcallbacks:
  - metrics: CategoricalAccuracy
    name: superacc/blk1_ratio1_valid
  - metrics: NLLError
    name: superloss/blk1_ratio1_valid
  subnet: blk1_ratio1
- callback: SubnetInferenceRunner
  split: valid
  subcallbacks:
  - metrics: CategoricalAccuracy
    name: superacc/blk2_ratio1_valid
  - metrics: NLLError
    name: superloss/blk2_ratio1_valid
  subnet: blk2_ratio1
- callback: SubnetInferenceRunner
  split: valid
  subcallbacks:
  - metrics: CategoricalAccuracy
    name: superacc/blk3_ratio1_valid
  - metrics: NLLError
    name: superloss/blk3_ratio1_valid
  subnet: blk3_ratio1
- callback: SubnetInferenceRunner
  split: valid
  subcallbacks:
  - metrics: CategoricalAccuracy
    name: superacc/blk4_ratio1_valid
  - metrics: NLLError
    name: superloss/blk4_ratio1_valid
  subnet: blk4_ratio1
- callback: SubnetInferenceRunner
  split: valid
  subcallbacks:
  - metrics: CategoricalAccuracy
    name: superacc/blk5_ratio1_valid
  - metrics: NLLError
    name: superloss/blk5_ratio1_valid
  subnet: blk5_ratio1
- callback: SubnetInferenceRunner
  split: valid
  subcallbacks:
  - metrics: CategoricalAccuracy
    name: superacc/blk6_ratio1_valid
  - metrics: NLLError
    name: superloss/blk6_ratio1_valid
  subnet: blk6_ratio1
- callback: SubnetInferenceRunner
  split: valid
  subcallbacks:
  - metrics: CategoricalAccuracy
    name: superacc/blk7_ratio1_valid
  - metrics: NLLError
    name: superloss/blk7_ratio1_valid
  subnet: blk7_ratio1
- callback: SubnetInferenceRunner
  split: valid
  subcallbacks:
  - metrics: CategoricalAccuracy
    name: superacc/blk1_rand2_valid
  - metrics: NLLError
    name: superloss/blk1_rand2_valid
  subnet: sharefront0_blk1_rand2
- callback: SubnetInferenceRunner
  split: valid
  subcallbacks:
  - metrics: CategoricalAccuracy
    name: superacc/blk2_rand2_valid
  - metrics: NLLError
    name: superloss/blk2_rand2_valid
  subnet: sharefront0_blk2_rand2
- callback: SubnetInferenceRunner
  split: valid
  subcallbacks:
  - metrics: CategoricalAccuracy
    name: superacc/blk3_rand2_valid
  - metrics: NLLError
    name: superloss/blk3_rand2_valid
  subnet: sharefront0_blk3_rand2
- callback: SubnetInferenceRunner
  split: valid
  subcallbacks:
  - metrics: CategoricalAccuracy
    name: superacc/blk4_rand2_valid
  - metrics: NLLError
    name: superloss/blk4_rand2_valid
  subnet: sharefront0_blk4_rand2
- callback: SubnetInferenceRunner
  split: valid
  subcallbacks:
  - metrics: CategoricalAccuracy
    name: superacc/blk5_rand2_valid
  - metrics: NLLError
    name: superloss/blk5_rand2_valid
  subnet: sharefront0_blk5_rand2
- callback: SubnetInferenceRunner
  split: valid
  subcallbacks:
  - metrics: CategoricalAccuracy
    name: superacc/blk6_rand2_valid
  - metrics: NLLError
    name: superloss/blk6_rand2_valid
  subnet: sharefront0_blk6_rand2
- callback: SubnetInferenceRunner
  split: valid
  subcallbacks:
  - metrics: CategoricalAccuracy
    name: superacc/blk7_rand2_valid
  - metrics: NLLError
    name: superloss/blk7_rand2_valid
  subnet: sharefront0_blk7_rand2
- callback: SubnetInferenceRunner
  split: valid
  subcallbacks:
  - metrics: CategoricalAccuracy
    name: superacc/blk8_rand2_valid
  - metrics: NLLError
    name: superloss/blk8_rand2_valid
  subnet: sharefront0_blk8_rand2
- callback: MaxSaver
  name: superacc/largest_valid
- callback: Saver
  max_to_keep: 10
ckpt:
  load_ckpt: true
  load_trainer: false
  name: checkpoints/step-18400.pt
criterion:
  name: nll
dataset:
  binarize: false
  binarize_threshold: 0.1307
  center_crop: 24
  digits_of_interest:
  - 0
  - 1
  - 2
  - 3
  fashion: false
  input_name: image
  n_test_samples: null
  n_valid_samples: 500
  name: mnist
  resize: 28
  resize_mode: bilinear
  root: examples/data
  split: valid
  target_name: digit
  train_valid_split_ratio:
  - 0.95
  - 0.05
debug:
  pdb: false
  seed: 42
  set_seed: true
es:
  crossover_size: 10
  est_success_rate: false
  eval:
    bsz: qiskit_max
    n_test_samples: 150
    use_noise_model: false
    use_real_qc: false
  gene_mask: null
  mutation_prob: 0.4
  mutation_size: 20
  n_iterations: 40
  parent_size: 10
  population_size: 40
  random_search: false
  score_mode: loss_succ
get_n_params: false
legalization:
  epoch_interval: 9999999999
  legalize: false
  step_interval: 9999999999
model:
  arch:
    down_sample_kernel_size: 6
    encoder_op_list_name: 4x4_ryzxy
    n_blocks: 8
    n_front_share_blocks: 1
    n_front_share_ops: 1
    n_front_share_wires: 1
    n_layers_per_block: 2
    n_wires: 4
    q_layer_name: u3cu3_s0
  load_op_list: false
  name: super_qfc0
  sampler:
    strategy:
      name: plain
  transpile_before_run: false
optimizer:
  lambda_lr: 0.01
  lr: 5e-3
  name: adam
  weight_decay: 0.0001
prune:
  eval:
    remove_ops: false
    remove_ops_thres: null
qiskit:
  backend_name: ibmq_quito
  basis_gates_name: null
  est_success_rate: false
  initial_layout: null
  max_jobs: 20
  n_shots: 8192
  noise_model_name: ibmq_quito
  optimization_level: 2
  seed_simulator: 42
  seed_transpiler: 42
  use_qiskit: true
  use_real_qc: false
regularization:
  unitary_loss: false
  unitary_loss_lambda: 0
  unitary_loss_lambda_trainable: false
run:
  bsz: 10000
  device: gpu
  n_epochs: 200
  n_warm_epochs: 30
  workers_per_gpu: 8
scheduler:
  name: cosine_warm
trainer:
  act_quant: false
  act_quant_loss: true
  act_quant_loss_lambda: 10
  act_quant_skip_last_node: true
  add_noise: false
  name: q_trainer
verbose: false
