model:
  arch:
    sample_arch:  [14, 0,
                   0, 0,
                   0, 0,
                   0, 0,
                   0, 0,
                   0, 0,
                   0, 0,
                   0, 0,
                   1]
