dataset:
  name: vowel
  root: 'examples/vowel_data'
  test_ratio: 0.3
  train_valid_split_ratio: [0.85, 0.15]
  resize: 10
  binarize: False
  binarize_threshold: null
  digits_of_interest: [0，5，1，6，2，7，3，4，8，9，10]
  input_name: vowel
  target_name: digit

model:
  arch:
    down_sample_kernel_size: null

criterion:
  name: nll

optimizer:
  name: adam
  lr: 5e-3
  weight_decay: 1.0e-4
  lambda_lr: 1.e-2

scheduler:
  name: cosine

trainer:
  name: q_trainer
  add_noise: False
  act_quant: False
  act_quant_skip_last_node: True
  act_quant_loss: True
  act_quant_loss_lambda: 10

run:
  n_epochs: 200
  n_warm_epochs: 0
  bsz: 4
  workers_per_gpu: 8
  device: gpu

debug:
  pdb: False
  set_seed: True
  seed: 42

regularization:
  unitary_loss: False
  unitary_loss_lambda_trainable: False
  unitary_loss_lambda: 0

legalization:
  legalize: False
  epoch_interval: 9999999999
  step_interval: 9999999999

callbacks:
  - callback: 'InferenceRunner'
    split: 'valid'
    subcallbacks:
      - metrics: 'CategoricalAccuracy'
        name: 'acc/valid'
      - metrics: 'NLLError'
        name: 'loss/valid'
  - callback: 'InferenceRunner'
    split: 'test'
    subcallbacks:
      - metrics: 'CategoricalAccuracy'
        name: 'acc/test'
      - metrics: 'NLLError'
        name: 'loss/test'
  - callback: 'MaxSaver'
    name: 'acc/valid'
  - callback: 'Saver'
    max_to_keep: 10

qiskit:
  use_qiskit: False
  use_real_qc: False
  backend_name: null
  noise_model_name: null
  coupling_map_name: null
  basis_gates_name: null
  n_shots: 8192
  initial_layout: null
  seed_transpiler: 42
  seed_simulator: 42
  optimization_level: 0
  est_success_rate: False
  max_jobs: 1

ckpt:
  load_ckpt: False
  load_trainer: False
  name: 'checkpoints/max-acc-valid.pt'

verbose: False

get_n_params: False

prune:
  eval:
    remove_ops: False
    remove_ops_thres: null
